Miami
GTAmodding/re3 pull request #706
Opened 2020-09-18 16:20 UTC by theR4K

rework of processVehicle and processPlayerVehicleEngine functions in AudioLogic.cpp

2020-09-18 16:31 UTC, ShFil119 commented on src/audio/AudioLogic.cpp
> +			playerVeh = (CVehicle*)attachedTo;
we prefer to use `nil` instead of `NULL`

2020-09-18 16:31 UTC, ShFil119 commented on src/audio/AudioLogic.cpp
> +		params.m_pTransmission = veh->pHandling != NULL ? &veh->pHandling->Transmission : NULL;
+1

2020-09-18 16:31 UTC, ShFil119 commented on src/audio/AudioLogic.cpp
> +				//ProcessModelHeliVehicle(this, &params);
why?

2020-09-18 16:31 UTC, ShFil119 commented on src/audio/AudioLogic.cpp
> +				ProcessCesna(&params);//recheck
imho it'd be better for these comments to be in header

2020-09-18 16:31 UTC, ShFil119 commented on src/audio/AudioLogic.cpp
> +				m_sQueueSample.m_fDistance = sqrt(params->m_fDistance);
float based const

Also we have wrappers for sqrt: `Sqrt`.

2020-09-18 16:31 UTC, ShFil119 commented on src/audio/AudioLogic.cpp
> +		tmp = 2526;
it sounds like sound length?

2020-09-18 16:31 UTC, ShFil119 commented on src/audio/AudioLogic.cpp
> +		bPlayerJustEnteredCar = 0;
why?

2020-09-18 16:31 UTC, ShFil119 commented on src/audio/AudioLogic.cpp
> +				cAudioManager::TranslateEntity(&m_sQueueSample.m_vecPos, &pos);
why?

2020-09-19 12:40 UTC, Sergeanur requested changes

2020-09-19 12:40 UTC, Sergeanur commented on src/audio/AudioManager.h
> +	void UpdateGasPedalAudio(float* gasPedalAudio, float vehGasPedal);
This function takes (CVehicle*, int)

2020-09-19 12:40 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +void cAudioManager::ProcessVehicle(CVehicle* veh)
What's with the format change?

2020-09-19 12:40 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +cAudioManager::UpdateGasPedalAudio(float* gasPedalAudio, float vehGasPedal)
This function takes (CVehicle*, int)

2020-09-19 12:40 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +	soundOffset = 3 * (engineSoundType - 4);
CAR_SAMPLEBANKS_OFFSET should stay and be adjusted

2020-09-19 12:40 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +	switch (soundOffset) {
This was probably optimized engineSoundType switch (thus should be enum)

2020-09-19 12:40 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +	switch (engineSoundType) {
Should use enum (probably banks)

2020-09-19 12:40 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +				if (engineSoundType == SAMPLEBANK_CAR_COBRA)
This is still MACKTRUCK, not COBRA. Enum should be adjusted instead

2020-09-19 12:40 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +		if (engineSoundType == SAMPLEBANK_CAR_COBRA)
same as above

2020-09-19 12:40 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +					if (engineSoundType != 15 && engineSoundType != 16)
Should use enum

2020-09-19 12:40 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +				if (engineSoundType == SAMPLEBANK_CAR_COBRA)
MACKTRUCK

2020-09-19 12:40 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +					if (engineSoundType == 8)
MACKTRUCK

2020-09-19 12:40 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +					if (engineSoundType == 8)
MACKTRUCK

2020-09-19 12:40 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +					if (engineSoundType == 8)
MACKTRUCK

2020-09-19 12:40 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +				if (engineSoundType == 8)
MACKTRUCK

2020-09-20 23:51 UTC, theR4K commented on src/audio/AudioLogic.cpp
> +cAudioManager::UpdateGasPedalAudio(float* gasPedalAudio, float vehGasPedal)
Actually it's takes (CVehicle*, eVehicleType)

2020-09-20 23:57 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +cAudioManager::UpdateGasPedalAudio(float* gasPedalAudio, float vehGasPedal)
enums are reflected in symbols, so it was just int

2020-09-21 00:09 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +		if (dist <= 0.0)
Possibly better to reverse this check, also missing `f`

2020-09-21 00:09 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +cAudioManager::ProcessVehicleEngine1(cVehicleParams* params)
ProcessVehicleEngine**1**???

2020-09-21 00:09 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +				for (uint8 i = 0; i < 4; i++) {
Why change that?

2020-09-21 00:11 UTC, theR4K commented on src/audio/AudioLogic.cpp
> +				for (uint8 i = 0; i < 4; i++) {
bcs sizeof(tWheelState*) it's not same with sizeof(array)

2020-09-21 00:14 UTC, theR4K commented on src/audio/AudioLogic.cpp
> +cAudioManager::ProcessVehicleEngine1(cVehicleParams* params)
this commit created when I complete function, but not check if statements on errors. so 1 appears bcs I want to compare old and new function/

2020-09-21 00:15 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +				for (uint8 i = 0; i < 4; i++) {
Ah, it's a pointer now, I see

2020-09-21 16:55 UTC, Sergeanur approved these changes

2020-09-21 16:55 UTC, merged