Helicopters not ringing, and other audio stuff
GTAmodding/re3 pull request #717
Opened 2020-09-26 17:52 UTC by theR4K

2020-09-26 23:31 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +void
This returns bool

2020-09-26 23:37 UTC, Sergeanur requested changes

2020-09-26 23:37 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +		emittingVol = (m_sQueueSample.m_fDistance - 25.0f) * 0.06666667f * (75.0f * propellerSpeed);
`* 0.06666667f` is `/ 15.0f`

2020-09-26 23:37 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +	if (params->m_fDistance >= 19600.0f)
SQ(140.0f)

2020-09-26 23:37 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +				m_sQueueSample.m_nFrequency = 18000 + Min(1.0f, freqModifier * (Max(accelerateState, brakeState) / 255.0f)) * 2204;
Looks like this if-else should be reversed

2020-09-26 23:37 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +			m_sQueueSample.m_nFrequency = clamp(m_sQueueSample.m_nFrequency, freqFrontPrev - 197, freqFrontPrev + 197);
clamp isn't what originally done here, right? Best to keep original way then

2020-09-26 23:37 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +				m_sQueueSample.m_nFrequency = 9000 + Min(1.0f, (Max(accelerateState, brakeState) / 255) * freqModifier) * 1102;
Again reversed if-else

2020-09-26 23:37 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +				if (accelerateState <= 0 && brakeState <= 0)
and again

2020-09-26 23:37 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +		if (params->m_fDistance < 729.0f) {
SQ(27)

2020-09-26 23:37 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +CVector aVecExtraSoundPosition[] = { {-1042.546f, 88.793999f, 11.324f}, {-1004.476f, 181.69701f, 11.324f} };
88.793999f is 88.794f and 181.69701f is 181.697f

2020-09-26 23:43 UTC, Sergeanur commented on src/render/Fluff.h
> +	CVector GetPosition() { return m_midPoint; };
const CVector &

2020-09-26 23:44 UTC, Sergeanur commented on src/render/Fluff.h
> +	static CEscalator GetEscalator(int ind) { return aEscalators[ind]; };
const CEscalator &

2020-09-26 23:46 UTC, theR4K commented on src/audio/AudioLogic.cpp
> +			m_sQueueSample.m_nFrequency = clamp(m_sQueueSample.m_nFrequency, freqFrontPrev - 197, freqFrontPrev + 197);
originally hire used
if(freq < freqFrontPrev){
   if(freq < freqFrontPrev - 197)
       freq = freqFrontPrev - 197;
}else{
    if(freq > freqFrontPrev + 197)
        freq = freqFrontPrev + 197;
}
but this is clear clamp. But it's use one more compare....

2020-09-26 23:53 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +			m_sQueueSample.m_nFrequency = clamp(m_sQueueSample.m_nFrequency, freqFrontPrev - 197, freqFrontPrev + 197);
Yeah the first check shows that it wasn't clamp macro

2020-09-27 00:04 UTC, theR4K commented on src/audio/AudioLogic.cpp
> +			m_sQueueSample.m_nFrequency = clamp(m_sQueueSample.m_nFrequency, freqFrontPrev - 197, freqFrontPrev + 197);
but this is it

2020-09-27 00:05 UTC, theR4K commented on src/audio/AudioLogic.cpp
> +			m_sQueueSample.m_nFrequency = clamp(m_sQueueSample.m_nFrequency, freqFrontPrev - 197, freqFrontPrev + 197);
all this code looks like macro, bcs Its repeating 3 times

2020-09-27 00:09 UTC, theR4K commented on src/audio/AudioLogic.cpp
> +void
this bool means nothing, bcs it false only if distance too big

2020-09-27 00:33 UTC, theR4K commented on src/render/Fluff.h
> +	static CEscalator GetEscalator(int ind) { return aEscalators[ind]; };
cant be const

2020-09-27 00:35 UTC, ShFil119 commented on src/render/Fluff.h
> +	static CEscalator GetEscalator(int ind) { return aEscalators[ind]; };
reference

2020-09-27 00:39 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +			m_sQueueSample.m_nFrequency = clamp(m_sQueueSample.m_nFrequency, freqFrontPrev - 197, freqFrontPrev + 197);
But it still ain't clamp macro

2020-09-27 00:39 UTC, Sergeanur commented on src/render/Fluff.h
> +	static CEscalator GetEscalator(int ind) { return aEscalators[ind]; };
Is it being changed in audio code or why it can't be const?

2020-09-27 00:43 UTC, ShFil119 commented on src/audio/AudioLogic.cpp
> +	if (modifier > 0.01) { //mb can be replaced by (emittingVol > 1)
`0.01f`

2020-09-27 00:43 UTC, ShFil119 commented on src/audio/AudioLogic.cpp
> +		emittingVol = (100.0 * modifier);
also

2020-09-27 00:43 UTC, ShFil119 commented on src/audio/AudioLogic.cpp
> +			if (distance > 0.0)
+1

2020-09-27 00:46 UTC, theR4K commented on src/render/Fluff.h
> +	static CEscalator GetEscalator(int ind) { return aEscalators[ind]; };
ask compiler... I'm C# developer)

2020-09-28 17:41 UTC, erorcun commented on src/audio/AudioLogic.cpp
> +			const float SOUND_INTENSITY = 35.0f;
heliIndex should be declared in here

2020-09-28 17:59 UTC, erorcun commented on src/audio/AudioLogic.cpp
> +			m_sQueueSample.m_vecPos = { 0.0f, -10.0f, 0.0f }; //this is from android, but for real it's not used
we don't prefer new C++ things

2020-09-28 18:08 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +				if (accelerateState <= 0 && brakeState <= 0)
unreversed check

2020-09-28 22:48 UTC, merged