more audio for god of audio
GTAmodding/re3 pull request #771
Opened 2020-10-17 13:59 UTC by theR4K

2020-10-17 14:13 UTC, theR4K commented on src/audio/AudioLogic.cpp
> +		isPlayerVeh = CWorld::Players[CWorld::PlayerInFocus].m_pRemoteVehicle != nil;  //mb bug?
looks like we need compare it with params.m_pVehicle

2020-10-17 14:13 UTC, theR4K commented on src/audio/AudioLogic.cpp
> +				modificator = (m_sQueueSample.m_fDistance / 95.0f) * 0.5f;   //mb SOUND_INTENSITY?
seems it's divided by SOUND_INTENSITY

2020-10-17 14:13 UTC, theR4K commented on src/audio/AudioLogic.cpp
> +			modificator = (m_sQueueSample.m_fDistance / 30.0f) * 0.5f; //need recheck in III, mb sount_intensity?
same as above and also need check it in reIII

2020-10-17 14:13 UTC, theR4K commented on src/audio/AudioLogic.cpp
> +			m_sQueueSample.m_nEmittingVolume = 80; //mb bug?
we use different volume if car drowning but for some reason not hire

2020-10-17 14:13 UTC, theR4K commented on src/audio/AudioLogic.cpp
> +			m_sQueueSample.m_nEmittingVolume = 60; //mb bug?
same as above

2020-10-17 14:13 UTC, theR4K commented on src/audio/AudioLogic.cpp
> +					m_sQueueSample.m_fSoundIntensity = SOUND_INTENSITY;  //BUG IN III!!!!
in reIII SOUND_INTENSITY constant squared why?

2020-10-17 14:13 UTC, theR4K commented on src/audio/AudioLogic.cpp
> +			m_sQueueSample.m_vecPos = CProjectileInfo::ms_apProjectile[i]->GetPosition(); //??
I cant check if it call this func

2020-10-17 16:08 UTC, erorcun commented on src/audio/AudioLogic.cpp
> +		isPlayerVeh = CWorld::Players[CWorld::PlayerInFocus].m_pRemoteVehicle != nil;  //mb bug?
yeah this looks like a bug

2020-10-17 16:27 UTC, jte commented on src/audio/AudioLogic.cpp
> +	params->m_pVehicle->UsesSiren();
return

2020-10-17 16:41 UTC, erorcun commented on src/audio/AudioLogic.cpp
> +				modificator = (m_sQueueSample.m_fDistance / 95.0f) * 0.5f;   //mb SOUND_INTENSITY?
yeah I think same. and I suggest naming it `multiplier` or `mult`

2020-10-17 16:41 UTC, erorcun commented on src/audio/AudioLogic.cpp
> +			m_sQueueSample.m_nEmittingVolume = 80; //mb bug?
yeah looks like a bug

2020-10-17 16:41 UTC, erorcun commented on src/audio/AudioLogic.cpp
> +			m_sQueueSample.m_nEmittingVolume = 60; //mb bug?
also looks like a bug

2020-10-17 16:41 UTC, erorcun commented on src/audio/AudioLogic.cpp
> +					m_sQueueSample.m_fSoundIntensity = SOUND_INTENSITY;  //BUG IN III!!!!
I think 30.f was both volume and distance in here, and compiler optimized it into one variable

2020-10-17 16:41 UTC, erorcun commented on src/audio/AudioLogic.cpp
> +			m_sQueueSample.m_vecPos = CProjectileInfo::ms_apProjectile[i]->GetPosition(); //??
yes, Projectile is an Object and we use GetPosition() for matrix.pos

2020-10-17 16:59 UTC, theR4K commented on src/audio/AudioLogic.cpp
> +					m_sQueueSample.m_fSoundIntensity = SOUND_INTENSITY;  //BUG IN III!!!!
no, you need see value of SOUND_INTENSITY in reIII it's 900

2020-10-17 17:03 UTC, theR4K commented on src/audio/AudioLogic.cpp
> +	params->m_pVehicle->UsesSiren();
thanks! I know, this PR WIP for now

2020-10-25 22:45 UTC, Nick007J commented on src/audio/AudioLogic.cpp
> +				m_nPlayerMood = (playerPed->m_pWanted->m_nWantedLevel > 3) ? 2 : 1;
I would strongly suggest enums, especially since we have actual original ones for player mood

2020-11-01 19:14 UTC, Nick007J commented on src/audio/AudioLogic.cpp
> -			case NEW_DOOR:
I believe change isn't accurate - NEW_DOOR is handled in switch, just IDA decided to unite it with default. I suggest bringing the old layout back, because it would have been strange for enum not to be handled.

2020-11-01 19:16 UTC, Nick007J commented on src/audio/AudioLogic.cpp
> +			m_sQueueSample.m_nCounter = event + 22;
Eeh, this also isn't true to be pedantic, they did not store the event and calculate it twice, but this is less important.

2020-11-01 19:28 UTC, theR4K commented on src/audio/AudioLogic.cpp
> -			case NEW_DOOR:
yep, you right. But I think better if I just add NEW_DOOR separate from default...

2020-11-01 19:32 UTC, Nick007J commented on src/audio/AudioLogic.cpp
> +	} else 	if (position <= TakeOffPoint + 300.0f) {
extra space

2020-11-01 19:33 UTC, Nick007J approved these changes

2020-11-01 19:34 UTC, theR4K commented on src/audio/AudioLogic.cpp
> +			m_sQueueSample.m_nCounter = event + 22;
I'm also seen when event calculated twice, and I can't understand what I need to to with that? On one side use event variable, bcs it's doesn't change  anything. On other side use code with two calculations, but this make code less readable. So I prefer use event variable, and I can understand if I need mark it as bug_fix or so. Mb just left comment hire?

2020-11-01 19:41 UTC, theR4K commented on src/audio/AudioLogic.cpp
> +	} else 	if (position <= TakeOffPoint + 300.0f) {
it's tab, lol

2020-11-01 21:22 UTC, ShFil119 approved these changes
nice work

2020-11-02 07:39 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +	m_nPlayerMood = 0;
Must use enum

2020-11-02 07:39 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +cAudioManager::ProcessRainOnVehicle(cVehicleParams* params)
What's with the format change?

2020-11-02 07:42 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +				if (isHeli) {
Leave it uncommented

2020-11-02 07:43 UTC, Sergeanur commented on src/audio/AudioManager.cpp
> +	m_FrameCounter++;
Not needed

2020-11-02 07:50 UTC, theR4K commented on src/audio/AudioLogic.cpp
> +cAudioManager::ProcessRainOnVehicle(cVehicleParams* params)
vs automatic

2020-11-02 07:51 UTC, theR4K commented on src/audio/AudioManager.cpp
> +	m_FrameCounter++;
but exist originally

2020-11-02 07:53 UTC, Sergeanur commented on src/audio/AudioManager.cpp
> +	m_FrameCounter++;
Nope

2020-11-02 07:55 UTC, theR4K commented on src/audio/AudioLogic.cpp
> +				if (isHeli) {
Hmm, I don't think so. Bcs it's looks like trash after resolve gotos

2020-11-02 08:03 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +				if (isHeli) {
Just keep the original logic

2020-11-02 08:45 UTC, theR4K commented on src/audio/AudioLogic.cpp
> +				if (isHeli) {
it's is it

2020-11-03 08:39 UTC, Sergeanur requested changes

2020-11-03 08:39 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +#endif
Shouldn't we check if current vehicle is player's vehicle?

2020-11-03 08:39 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +#endif
same question

2020-11-03 08:39 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +cAudioManager::ProcessVehicleRoadNoise(cVehicleParams* params)
Format

2020-11-03 08:39 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +cAudioManager::ProcessWetRoadNoise(cVehicleParams* params)
Format

2020-11-03 08:39 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +cAudioManager::GetVehicleDriveWheelSkidValue(CVehicle* veh, tWheelState wheelState, float gasPedalAudio, cTransmission *transmission, float velocityChange)
Format

2020-11-03 08:39 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +cAudioManager::ProcessVehicleHorn(cVehicleParams* params)
Format

2020-11-03 08:39 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +cAudioManager::ProcessVehicleSirenOrAlarm(cVehicleParams* params)
Format

2020-11-03 08:39 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +						if (playerVeh == 0 && playerPed != 0) {
nil check

2020-11-03 08:39 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +cAudioManager::ProcessJumbo(cVehicleParams* params)
Format

2020-11-03 08:39 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +	CPlane* plane;
Format

2020-11-03 08:39 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +
Please make this the original logic like I told you

2020-11-03 08:39 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +			CPlayerPed* playerPed;
Format

2020-11-03 08:39 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +	CVehicle* veh;
Format

2020-11-03 08:39 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +	CVehicle* veh;
Format

2020-11-03 08:39 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +	CPlayerPed* playerPed;
Format

2020-11-03 08:39 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +	CPlayerPed* playerPed;
Format

2020-11-04 08:35 UTC, theR4K commented on src/audio/AudioLogic.cpp
> +
it's orig. see android

2020-11-04 08:40 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +
No, android is optimized

2020-11-08 14:37 UTC, erorcun commented on src/audio/AudioLogic.cpp
> +				//mb error in III
?

2020-11-08 14:37 UTC, erorcun commented on src/control/Script.h
> +	static uint32* GetLastMissionPassedTime() { return &LastMissionPassedTime; }
I can't say I liked that. I think you should do it reference

2020-11-08 14:37 UTC, erorcun commented on src/audio/AudioLogic.cpp
> +		modificator = Min(1.0f, (plane->m_fSpeed - 0.103344f) * 1.6760077f);
uh, are we sure those numbers mean nothing?

2020-11-08 14:55 UTC, theR4K commented on src/audio/AudioLogic.cpp
>  cAudioManager::ProcessRainOnVehicle(cVehicleParams *params)
yep, same in III. I will change)

2020-11-08 14:59 UTC, theR4K commented on src/control/Script.h
> +	static uint32* GetLastMissionPassedTime() { return &LastMissionPassedTime; }
lol, I ask about that two weeks ago!

2020-11-08 15:28 UTC, theR4K commented on src/audio/AudioLogic.cpp
> +		if (acceletateState < brakeState)
1050

2020-11-08 15:31 UTC, theR4K commented on src/audio/AudioLogic.cpp
> +				//mb error in III
I don't remember or it's about removed line. OR it's about emitting volume

2020-11-08 15:33 UTC, theR4K commented on src/audio/AudioLogic.cpp
> +
DON"T TOUCH THAT! EVER!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

2020-11-08 15:34 UTC, theR4K commented on src/audio/AudioLogic.cpp
> +				//mb error in III
yep, I ask hire to check if "m_sQueueSample.m_nFrequency += i * (m_sQueueSample.m_nFrequency / 64)" exists it III...

2020-11-08 15:35 UTC, Sergeanur commented on src/audio/AudioLogic.cpp
> +
Well then fix it

2020-11-08 15:35 UTC, theR4K commented on src/audio/AudioLogic.cpp
> +		modificator = Min(1.0f, (plane->m_fSpeed - 0.103344f) * 1.6760077f);
I can't find any explanations...

2020-11-08 16:05 UTC, theR4K commented on src/audio/AudioLogic.cpp
> +
nothing to fix lol. Maximum that I can it's mark it by comment

2020-11-08 18:17 UTC, erorcun commented on src/audio/AudioLogic.cpp
> +		if (acceletateState < brakeState)
I know, but let's do it in original way with DotProduct :)

2020-11-08 18:17 UTC, erorcun commented on src/audio/AudioLogic.cpp
> +				//mb error in III
what? I mean why do you leave "mb" comment in the code :smile:  doesn't it mean "my bad"?

2020-11-08 19:02 UTC, theR4K commented on src/audio/AudioLogic.cpp
> +				//mb error in III
it's may be

2020-11-08 19:03 UTC, theR4K commented on src/audio/AudioLogic.cpp
> +		if (acceletateState < brakeState)
hmm, for some reason I think it's same. Ok

2020-11-08 19:35 UTC, theR4K commented on src/audio/AudioLogic.cpp
> +
I think we can close this page

2020-11-08 19:36 UTC, theR4K commented on src/audio/AudioLogic.cpp
> +				//mb error in III
So FireHead check it. So this line removed in VC. This Comment not needed anymore

2020-11-10 20:32 UTC, merged