Fluff done
GTAmodding/re3 pull request #778
Opened 2020-10-20 23:07 UTC by majesticCoding

2020-10-22 20:47 UTC, erorcun requested changes

2020-10-22 20:47 UTC, erorcun commented on src/render/Fluff.cpp
> +	for (int32 i = 0; i < 3; i++) {
let's add NUM_LEVELS to eLevelName and replace 3 with it

2020-10-22 20:47 UTC, erorcun commented on src/render/Fluff.cpp
> +			aMovingThings[i].Update();
this shouldn't be in this func.

2020-10-22 20:47 UTC, erorcun commented on src/render/Fluff.cpp
> +		float angle = (CTimer::GetTimeInMilliseconds() % 0x3FFF) * 0.0003835f;
0.0003835f = TWOPI / 0x3FFF

2020-10-22 20:47 UTC, erorcun commented on src/render/Fluff.cpp
> +					CCoronas::RegisterCorona((uintptr)&m_pEntity + 1, 128, 128, 100, 255, coors, 70.0f, 600.0f, 0.0f, CCoronas::TYPE_STAR, CCoronas::REFLECTION_OFF, CCoronas::LOSCHECK_OFF, CCoronas::STREAK_OFF, 0.0
first parameter should be just 43

2020-10-22 20:47 UTC, erorcun commented on src/render/Fluff.cpp
> +		float angle = (CTimer::GetTimeInMilliseconds() % 0x7FF) * 0.003068f;
this is TWOPI / 0x7FF

2020-10-22 20:47 UTC, erorcun commented on src/render/Fluff.cpp
> +		float angle = (CTimer::GetTimeInMilliseconds() % 0x3FF) * 0.006136f;
TWOPI / 0x3FF

2020-10-22 20:47 UTC, erorcun commented on src/render/Fluff.cpp
> +		float angle = (CTimer::GetTimeInMilliseconds() % 0x3FFFF) * 0.000024f;
TWOPI / 0x3FFFF

2020-10-22 20:47 UTC, erorcun commented on src/render/Fluff.cpp
> +void CMovingThings::RegisterOne(int16 nType, CEntity *pEnt) {
pls use original signature

2020-10-22 20:47 UTC, erorcun commented on src/render/Fluff.cpp
> +		RegisterOne(2, pEnt);
also those `if`s after the first if should be `else if`

2020-10-22 20:47 UTC, erorcun commented on src/render/Fluff.cpp
> +void CScrollBar::Init(CVector pos1, CVector pos2, uint8 type, uint8 red, uint8 green, uint8 blue, float scale)
looks like there is some missing bits in this func. and after doing it you will notice struct has changed since III

2020-10-22 20:47 UTC, erorcun commented on src/render/Fluff.cpp
> +				default:
this is case 3. default is just `break`.

2020-10-23 03:48 UTC, majesticCoding commented on src/render/Fluff.cpp
> +void CScrollBar::Init(CVector pos1, CVector pos2, uint8 type, uint8 red, uint8 green, uint8 blue, float scale)
can't see any other fields or smth like that
The only distinction I see is that the size assignment, which is scaled difference between two points now

2020-10-23 13:27 UTC, majesticCoding commented on src/render/Fluff.cpp
> +void CScrollBar::Init(CVector pos1, CVector pos2, uint8 type, uint8 red, uint8 green, uint8 blue, float scale)
the string doesn't work correct with it
looks like it takes strlen from ". ", not from m_pMessage, hence it equals 2. The same thing in gta3

2020-10-23 13:27 UTC, majesticCoding commented on src/render/Fluff.cpp
> +void CMovingThings::RegisterOne(CEntity *pEnt, uint8 nType) {
fixed

2020-10-23 13:51 UTC, erorcun commented on src/render/Fluff.cpp
> +void CScrollBar::Init(CVector pos1, CVector pos2, uint8 type, uint8 red, uint8 green, uint8 blue, float scale)
? isn't m_pMessage already ". "? I mean it's obvious that it will always be 2, but you should do it in original way

2020-10-23 14:50 UTC, majesticCoding commented on src/render/Fluff.cpp
> +void CScrollBar::Init(CVector pos1, CVector pos2, uint8 type, uint8 red, uint8 green, uint8 blue, float scale)
yeah, fixed

2020-10-23 14:59 UTC, erorcun approved these changes

2020-10-24 14:56 UTC, merged