CObject::Render
GTAmodding/re3 pull request #791
Opened 2020-10-28 12:04 UTC by majesticCoding

yacht particles

2020-10-29 20:31 UTC, Sergeanur requested changes

2020-10-29 20:31 UTC, Sergeanur commented on src/objects/Object.cpp
> +	RwRGBA color{ red, green, blue, alpha };
`RwRGBA color = { red, green, blue, alpha };`

2020-10-29 20:31 UTC, Sergeanur commented on src/objects/Object.cpp
> +			float posZ = scaleMax * this->GetForward().z + 2.25f * this->GetRight().z + this->GetPosition().z;
This looks like `CVector pos = scaleMax * GetForward() + 2.25f * GetRight() + GetPosition()`, same with the rest down below

2020-10-30 03:34 UTC, majesticCoding commented on src/objects/Object.cpp
> +	RwRGBA color{ red, green, blue, alpha };
fixed

2020-10-30 03:34 UTC, majesticCoding commented on src/objects/Object.cpp
> +			float posZ = scaleMax * this->GetForward().z + 2.25f * this->GetRight().z + this->GetPosition().z;
fixed

2020-10-31 16:59 UTC, aap commented on src/objects/Object.cpp
> +	int alpha = CGeneral::GetRandomNumberInRange(29, 196);
CGeneral::GetRandomNumberInRange(196, 225);

2020-10-31 16:59 UTC, aap commented on src/objects/Object.cpp
> +			float scaleMax = CModelInfo::GetModelInfo(this->GetModelIndex())->GetColModel()->boundingBox.max.y * 0.85f;
`float scaleMax = GetColModel()->boundingBox.max.y * 0.85f;`

2020-10-31 16:59 UTC, aap commented on src/objects/Object.cpp
> +		float moveSpeedMagnitude = this->GetMoveSpeed().Magnitude();
they actually recalculate this all the time...but i guess we don't have to do that too

2020-10-31 16:59 UTC, aap commented on src/objects/Object.cpp
> +			float pfOutLevel;
bad name, this is not a pointer. maybe just `float waterLevel;`?

2020-10-31 16:59 UTC, aap commented on src/objects/Object.cpp
> +			float scaleMin = CModelInfo::GetModelInfo(this->GetModelIndex())->GetColModel()->boundingBox.min.y;
see above

2020-10-31 16:59 UTC, aap commented on src/objects/Object.cpp
> +			float scaleMax = CModelInfo::GetModelInfo(this->GetModelIndex())->GetColModel()->boundingBox.max.y * 0.85f;
see above

2020-10-31 16:59 UTC, aap commented on src/objects/Object.cpp
> +			float scaleMin = CModelInfo::GetModelInfo(this->GetModelIndex())->GetColModel()->boundingBox.min.y;
see above

2020-10-31 16:59 UTC, aap commented on src/objects/Object.cpp
> +			CVector dir = this->GetMoveSpeed() + 0.3f * this->GetRight() - 0.5f * this->GetForward();
`- 0.3f ...`

2020-10-31 16:59 UTC, aap commented on src/objects/Object.cpp
> +			float pfOutLevel;
see above

2020-10-31 22:20 UTC, ShFil119 commented on src/objects/Object.cpp
> +	RwRGBA color = { red, green, blue, alpha };
It prevents building on mac. Casting each arg to uint8 should be easiest way to solve this issue.

2020-11-01 09:40 UTC, merged