CObject fixes
GTAmodding/re3 pull request #847
Opened 2020-11-29 07:39 UTC by waliedyassen

Fixes 1 bug with `CObject::DeleteAllTempObjectsInArea` and implements 3 missing behaviors for `MI_RCBOMB`, `MI_BEACHBALL`  and `MI_PETROLPUMP2`

2020-11-29 14:43 UTC, Sergeanur requested changes
Thank you for your contribution, there's a couple of things to be fixed though.

2020-11-29 14:43 UTC, Sergeanur commented on src/core/General.h
> +
We don't need this.

2020-11-29 14:43 UTC, Sergeanur commented on src/objects/Object.cpp
> +	auto mi = GetModelIndex();
We don't use auto.

2020-11-29 14:43 UTC, Sergeanur commented on src/objects/Object.cpp
> +		constexpr float BEACHBALL_DEACCELERATION = 2.5f;
We don't use constexpr. Use #define instead.

2020-11-29 14:43 UTC, Sergeanur commented on src/objects/Object.cpp
> +		float fTimeScale = powf(0.95, CTimer::GetTimeStep());
`Pow`. Also in here and other occasions below floating point value needs `f` suffix

2020-11-29 14:43 UTC, Sergeanur commented on src/objects/Object.cpp
> +					if (m_nBeachballBounces > 0) {
Missing turn speed calculation above this

2020-11-29 14:43 UTC, Sergeanur commented on src/objects/Object.cpp
> +						sprintf(gString, "%d", m_nBeachballBounces);
Missing another `if (m_nBeachballBounces > 0) {` above this.

2020-11-29 14:43 UTC, Sergeanur commented on src/objects/Object.cpp
> +			float distanceMagnitude = distance.Magnitude2D();
A bit of a nit, but original code didn't use variable in here and instead called `distance.Magnitude2D()` both times.

2020-11-29 14:43 UTC, Sergeanur commented on src/objects/Object.cpp
> +				m_vecMoveSpeed.y += CGeneral::GetRandomNumberInRangeInc(-3, 4) / 100.0;
```suggestion
				m_vecMoveSpeed.x += (CGeneral::GetRandomNumber() % 8 - 3) / 100.0f;
				m_vecMoveSpeed.y += (CGeneral::GetRandomNumber() % 8 - 3) / 100.0f;
```

2020-11-29 14:43 UTC, Sergeanur commented on src/objects/Object.cpp
> +				m_vecTurnSpeed.y += CGeneral::GetRandomNumberInRangeInc(-7, 8) / 10.0f;
```suggestion
				m_vecTurnSpeed.x += (CGeneral::GetRandomNumber() % 16 - 7) / 10.0f;
				m_vecTurnSpeed.y += (CGeneral::GetRandomNumber() % 16 - 7) / 10.0f;
```

2020-11-29 14:43 UTC, Sergeanur commented on src/objects/Object.cpp
> +				}
```suggestion
				m_nBeachballBounces++;
				m_nBeachballBounces = Max(m_nBeachballBounces, BEACHBALL_MAX_SCORE);
```

2020-11-29 14:43 UTC, Sergeanur commented on src/objects/Object.cpp
> +	}
Some flag code is missing in the end of function.

2020-11-29 14:46 UTC, ShFil119 commented on src/objects/Object.cpp
> +		constexpr float BEACHBALL_DEACCELERATION = 2.5f;
or just `static const`

2020-11-29 14:48 UTC, Sergeanur commented on src/objects/Object.cpp
> +		constexpr float BEACHBALL_DEACCELERATION = 2.5f;
But not in this occasion, please.

2020-11-30 00:46 UTC, waliedyassen commented on src/objects/Object.cpp
> +				}
Max wouldn't work there, I assume you meant Min instead

2020-11-30 01:13 UTC, Sergeanur commented on src/objects/Object.cpp
> +				}
Indeed

2020-12-01 10:23 UTC, aap commented on src/objects/Object.cpp
> +			default:
where is DAMAGE_EFFECT_SMASH_VEGPALM?

2020-12-01 10:52 UTC, waliedyassen commented on src/objects/Object.cpp
> +			if (distance.z > 0.0 && distance.z < 1.5f && distanceMagnitude < 1.0) {
It's used in the other condition, in the mobile binary they have it as a variable like this.

2020-12-01 10:58 UTC, aap commented on src/objects/Object.cpp
> +			if (distance.z > 0.0 && distance.z < 1.5f && distanceMagnitude < 1.0) {
That's a compiler optimization. the android compiler was much more aggressive

2020-12-01 11:02 UTC, waliedyassen commented on src/objects/Object.cpp
> +			if (distance.z > 0.0 && distance.z < 1.5f && distanceMagnitude < 1.0) {
Makes sense

2020-12-01 11:08 UTC, waliedyassen commented on src/objects/Object.cpp
> +				if (!GetIsStatic()) {
Are you sure about that one? Looks like it is the way it is right now for me.

2020-12-01 11:19 UTC, waliedyassen commented on src/objects/Object.cpp
> +				CBaseModelInfo *modelInfo = CModelInfo::GetModelInfo(GetModelIndex());
Will do, but that would not match the binary anymore, to be more accurate, in the binary it's something like this:
```cpp
CVector min = 0.85f * CModelInfo::GetModelInfo(GetModelIndex())->GetColModel()->boundingBox.min;
CVector max = 0.85f * CModelInfo::GetModelInfo(GetModelIndex())->GetColModel()->boundingBox.max;
```

2020-12-01 11:22 UTC, aap commented on src/objects/Object.cpp
> +				if (!GetIsStatic()) {
oh yeah, i got confused. logically this makes no sense to me. why would you remove non-static objects from the moving list???

2020-12-01 11:25 UTC, aap commented on src/objects/Object.cpp
> +				CBaseModelInfo *modelInfo = CModelInfo::GetModelInfo(GetModelIndex());
you don't have to go through modelinfo manually, GetColModel takes care of that. but yes, it looks like they didn't even use a temporary for the col model, so just
```
CVector min = 0.85f * GetColModel()->boundingBox.min;
CVector max = 0.85f * GetColModel()->boundingBox.max;
`

2020-12-02 00:35 UTC, waliedyassen commented on src/objects/Object.cpp
> +void *CObject::operator new(size_t sz) { return CPools::GetObjectPool()->New(); }
This was a revert to the style changes I did in a previous commit, I'll go through and make sure it is matching.

2020-12-06 22:35 UTC, Sergeanur commented on src/core/General.h
> +
Please remove this empty line change.

2020-12-06 22:45 UTC, waliedyassen commented on src/core/General.h
> +
Done

2020-12-06 22:48 UTC, Sergeanur commented on src/core/General.h
> +
Eh, now there's a change at the end of it (

2020-12-06 22:51 UTC, waliedyassen commented on src/core/General.h
> +
That matches the miami branch, the line was an extra line as well

2020-12-06 23:05 UTC, Sergeanur commented on src/core/General.h
> +
It wouldn't show it as a change if it's a match.

2020-12-06 23:16 UTC, waliedyassen commented on src/core/General.h
> +
Sorry, you are right. fixed it. But that's weird, it only shows when checking out locally. The empty lines are removed when viewing in the GitHub code viewer ([like here](https://github.com/GTAmodding/re3/blob/miami/src/core/General.h))

2020-12-07 14:14 UTC, Sergeanur approved these changes

2020-12-07 21:03 UTC, merged